name: Saviynt SS+Endpoint deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'

permissions:
  contents: read

jobs:
  plan:
    name: Terraform Plan (dev)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform/envs/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform/envs/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform/envs/dev
        env:
          TF_VAR_eic_url: ${{ secrets.SERVER_URL }}
          TF_VAR_eic_username: ${{ secrets.USERNAME }}
          TF_VAR_eic_password: ${{ secrets.PASSWORD }}
        run: terraform plan -var-file=dev.tfvars 



  apply:
    
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform/envs/dev
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform/envs/dev
        env:
          TF_VAR_eic_url: ${{ secrets.SERVER_URL }}
          TF_VAR_eic_username: ${{ secrets.USERNAME }}
          TF_VAR_eic_password: ${{ secrets.PASSWORD }}
        run: terraform apply -auto-approve -var-file=dev.tfvars 
